import type { FeedPost, ProfileSummary } from "@/lib/types";

export const sampleProfile: ProfileSummary = {
  id: "sample-user",
  handle: "petspace",
  displayName: "Petspace 官方",
  bio: "记录每一段温暖的宠物日常。",
  avatarUrl: null,
  avatarObjectKey: null,
  coverUrl: "/samples/walk-dog.png",
  coverObjectKey: null,
  profileViews: 1280,
  postsCount: 3,
  totalLikes: 586,
  totalViews: 9700,
  createdAt: new Date().toISOString(),
};

export const samplePosts: FeedPost[] = [
  {
    id: "sample-1",
    caption: "今天的散步路线多绕了一条街，结果收获了一整袋快乐。",
    imageUrl: "/samples/walk-dog.png",
    imageObjectKey: null,
    category: "daily",
    location: "城市公园",
    viewsCount: 4210,
    likesCount: 238,
    favoritesCount: 74,
    createdAt: new Date(Date.now() - 1000 * 60 * 24).toISOString(),
    author: {
      id: "sample-author-1",
      handle: "momo_daily",
      displayName: "Momo 和小伙伴",
      avatarUrl: "/samples/sofa-dog.png",
    },
    viewerHasLiked: false,
    viewerHasFavorited: true,
  },
  {
    id: "sample-2",
    caption: "午后阳光刚好，沙发被正式宣布为今天的宠物星球中心。",
    imageUrl: "/samples/window-cat.png",
    imageObjectKey: null,
    category: "home",
    location: "家里",
    viewsCount: 3115,
    likesCount: 186,
    favoritesCount: 52,
    createdAt: new Date(Date.now() - 1000 * 60 * 68).toISOString(),
    author: {
      id: "sample-author-2",
      handle: "sunny_cat",
      displayName: "小橘的窗台",
      avatarUrl: "/samples/window-cat.png",
    },
    viewerHasLiked: true,
    viewerHasFavorited: false,
  },
  {
    id: "sample-3",
    caption: "新玩具测试通过：耐咬、会响、能让主人笑出声。",
    imageUrl: "/samples/toy-dog.png",
    imageObjectKey: null,
    category: "play",
    location: "客厅",
    viewsCount: 2375,
    likesCount: 162,
    favoritesCount: 39,
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    author: {
      id: "sample-author-3",
      handle: "cookie_home",
      displayName: "Cookie 的家",
      avatarUrl: "/samples/toy-dog.png",
    },
    viewerHasLiked: false,
    viewerHasFavorited: false,
  },
];
